version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-service
      - KAFKA_BROKER_URL=kafka:9092
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - kafka
    networks:
      - app_network

  ride-matching-service:
    build: ./ride-matching-service
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/ride-matching-service
      - KAFKA_BROKER_URL=kafka:9092
    depends_on:
      - mongo
      - kafka
    networks:
      - app_network

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"
    networks:
      - app_network

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=200000000  # 200MB
      - KAFKA_MAX_REQUEST_SIZE=200000000  # 200MB
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - app_network

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
