version: "3.8"

services:
  auth-service:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/auth-service
      - KAFKA_BROKER_URL=kafka:9092
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  kafka:
    image: bitnami/kafka:latest
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
